esphome:
  name: hughes-power-watchdog

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: VERBOSE
  logs:
    esp32_ble_tracker: ERROR

external_components:
  - source:
      type: git
      url: https://github.com/spbrogan/esphome
      ref: PolledSensor
    components: [ hughes_power_watchdog ]
    refresh: 1s


# Enable Home Assistant API
api:

ota:
  password: !secret ota_pasword

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "yourssid"
    password: "yourpassword"

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: 0C:61:CF:32:4B:81
    id: power_watchdog
    
switch:
  - platform: ble_client
    ble_client_id: power_watchdog
    name: "Watchdog Monitoring"

sensor:
  - platform: hughes_power_watchdog
    ble_client_id: power_watchdog
    voltage_line_1:
      name: "Watchdog Voltage Line 1"
      accuracy_decimals: 0
    current_line_1:
      name: "Watchdog Current Line 1"
      accuracy_decimals: 1
    power_line_1:
      name: "Watchdog Power Line 1"
      accuracy_decimals: 0
    voltage_line_2:
      name: "Watchdog Voltage Line 2"
      accuracy_decimals: 0
    current_line_2:
      name: "Watchdog Current Line 2"
      accuracy_decimals: 1
    power_line_2:
      name: "Watchdog Power Line 2"
      accuracy_decimals: 0
    combined_power:
      name: "Watchdog Power"
      accuracy_decimals: 0
    total_power:
      name: "Watchdog Cumulative Power Usage"
      accuracy_decimals: 1
    error_code_value:
      name: "Watchdog Error Code"
    error_code_text:
      name: "Watchdog Error Text"
   
# Include sensors for troubleshooting
text_sensor:
  - platform: version
    name: Watchdog ESPHome Version
    id: watchdog_esphome_version
  - platform: wifi_info
    ip_address:
      name: Watchdog Host IP Address
      id: watchdog_host_ip
      icon: mdi:fingerprint
    ssid:
      name: Watchdog Host SSID
      id: watchdog_host_ssid
      icon: "mdi:router-wireless"
  - platform: template
    id: watchdog_host_mac_address
    name: Watchdog Monitor MAC Address
    lambda: 'return {WiFi.macAddress().c_str()};'
    icon: mdi:fingerprint
    update_interval: 1d
